### ISSUE TITLE
Assertion 'c' failed at ../src/pulse/subscribe.c:64, function pa_context_subscribe(). Aborting.

### ISSUE THREAD

**Issue by mavit** [mhthies/pulsectl-asyncio#16]
I'm trying to package pulsectl-asyncio for Fedora.  When I run the tests, `pulseaudio` crashes:

```specfile
%check
touch tests/__init__.py
%{py3_test_envvars} %{python3} -m unittest discover
```

```console
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.JhtEpN
+ umask 022
+ cd /builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
+ export FCFLAGS
+ VALAFLAGS=-g
+ export VALAFLAGS
+ RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Cforce-frame-pointers=yes -Clink-arg=-specs=/usr/lib/rpm/redhat/redhat-package-notes --cap-lints=warn'
+ export RUSTFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ cd pulsectl_asyncio-1.2.2
+ touch tests/__init__.py
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '
+ PATH=/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/BUILDROOT/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
+ PYTHONPATH=/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/BUILDROOT/usr/lib64/python3.13/site-packages:/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/BUILDROOT/usr/lib/python3.13/site-packages
+ PYTHONDONTWRITEBYTECODE=1
+ PYTEST_ADDOPTS=' --ignore=/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/pulsectl_asyncio-1.2.2/.pyproject-builddir'
+ PYTEST_XDIST_AUTO_NUM_WORKERS=8
+ /usr/bin/python3 -m unittest discover
/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/pulsectl_asyncio-1.2.2/tests/test_async_with_dummy_instance.py:31: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
.....Assertion 'c' failed at ../src/pulse/subscribe.c:64, function pa_context_subscribe(). Aborting.
/var/tmp/rpm-tmp.JhtEpN: line 54:   219 Aborted                 (core dumped) CFLAGS="${CFLAGS:-${RPM_OPT_FLAGS}}" LDFLAGS="${LDFLAGS:-${RPM_LD_FLAGS}}" PATH="/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/BUILDROOT/usr/bin:$PATH" PYTHONPATH="${PYTHONPATH:-/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/BUILDROOT/usr/lib64/python3.13/site-packages:/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/BUILDROOT/usr/lib/python3.13/site-packages}" PYTHONDONTWRITEBYTECODE=1 PYTEST_ADDOPTS="${PYTEST_ADDOPTS:-} --ignore=/builddir/build/BUILD/python-pulsectl-asyncio-1.2.2-build/pulsectl_asyncio-1.2.2/.pyproject-builddir" PYTEST_XDIST_AUTO_NUM_WORKERS="${PYTEST_XDIST_AUTO_NUM_WORKERS:-8}" /usr/bin/python3 -m unittest discover
error: Bad exit status from /var/tmp/rpm-tmp.JhtEpN (%check)
```

It's not obvious to me whether this is a genuine test failure or merely a problem with the test environment, but I thought it was worth reporting here just in case.

**Comment by mhthies** [comment]
From the program output it looks to me like the program crashes while executing the 6th unit tests (see 5 dots before the assertion error). The crash happens due to the C assertion in `pa_context_subscribe()` in libpulse which checks that the context pointer is not a null (see [subscribe.c:64](https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/pulse/subscribe.c?id=b096704c0d42c5e784deb781a07b23cfb5286a82#n64) in the current source).

We call `pa_context_subscribe()` from Python in `PulseAsync._event_mask_set()`, which is used by `PulseAsync.subscribe_events()` in two places: For setting up the event subscription and for resetting the subscribed events when the async interator over the events is somehow cancelled.

My first guess: The issue happens during teardown of the test: `PulseAsync.close()` disconnects from the PulseAudio server and resets `_ctx`. Due to the disconnect, a `PulseDisconnected` exception is raised in `PulseAsync.subscribe_events()` and its  the `finally` clause is executed. This calls `_event_mask_set()` but the `_ctx` is already `None`, which gets translated to a `nullptr` in C.

**Comment by mhthies** [comment]
I've added a potential fix for this crash to the latest release (1.3.0) of this package – assuming that my analysis in the comment above is correct.

@mavit, if you still – after those 1,5 years – have the setup to reproduce the crash in the tests, I'd be interested if the small fix was sufficient to avoid the crash.

**Comment by mavit** [comment]
The output is now more verbose, but the crash looks the same:

```console
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.NiInmB
+ umask 022
+ cd /builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  '
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  '
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules  '
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules  '
+ export FCFLAGS
+ VALAFLAGS=-g
+ export VALAFLAGS
+ RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Cforce-frame-pointers=yes -Clink-arg=-specs=/usr/lib/rpm/redhat/redhat-package-notes --cap-lints=warn'
+ export RUSTFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ cd pulsectl_asyncio-1.3.0
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  '
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  '
+ PATH=/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/BUILDROOT/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ PYTHONPATH=/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/BUILDROOT/usr/lib64/python3.15/site-packages:/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/BUILDROOT/usr/lib/python3.15/site-packages
+ PYTHONDONTWRITEBYTECODE=1
+ PYTEST_ADDOPTS=' --ignore=/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/.pyproject-builddir'
+ PYTEST_XDIST_AUTO_NUM_WORKERS=8
+ /usr/bin/python3 -m unittest discover
.....E...Task exception was never retrieved
future: <Task finished name='Task-61' coro=<AsyncDummyTests.test_get_peak_sample.<locals>.listen_stream_events() done, defined at /builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/pulsectl_asyncio-1.3.0/tests/test_async_with_dummy_instance.py:411> exception=PulseDisconnected() created at /builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/pulsectl_asyncio-1.3.0/tests/test_async_with_dummy_instance.py:419>
source_traceback: Object created at (most recent call last):
  File "<frozen runpy>", line 201, in _run_module_as_main
  File "<frozen runpy>", line 87, in _run_code
  File "/usr/lib64/python3.15/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib64/python3.15/unittest/main.py", line 104, in __init__
    self.runTests()
  File "/usr/lib64/python3.15/unittest/main.py", line 270, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib64/python3.15/unittest/runner.py", line 256, in run
    test(result)
  File "/usr/lib64/python3.15/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.15/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.15/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.15/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.15/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.15/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.15/unittest/case.py", line 747, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.15/unittest/async_case.py", line 147, in run
    return super().run(result)
  File "/usr/lib64/python3.15/unittest/case.py", line 691, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.15/unittest/async_case.py", line 102, in _callTestMethod
    result = self._callMaybeAsync(method)
  File "/usr/lib64/python3.15/unittest/async_case.py", line 128, in _callMaybeAsync
    return self._asyncioRunner.run(
  File "/usr/lib64/python3.15/asyncio/runners.py", line 127, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib64/python3.15/asyncio/base_events.py", line 711, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.15/asyncio/base_events.py", line 682, in run_forever
    self._run_once()
  File "/usr/lib64/python3.15/asyncio/base_events.py", line 2058, in _run_once
    handle._run()
  File "/usr/lib64/python3.15/asyncio/events.py", line 94, in _run
    self._context.run(self._callback, *self._args)
  File "/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/pulsectl_asyncio-1.3.0/tests/test_async_with_dummy_instance.py", line 419, in test_get_peak_sample
    loop.create_task(listen_stream_events())
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/pulsectl_asyncio-1.3.0/tests/test_async_with_dummy_instance.py", line 412, in listen_stream_events
    async for ev in pulse.subscribe_events('sink_input'):
    ...<3 lines>...
                break
  File "/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/pulsectl_asyncio-1.3.0/pulsectl_asyncio/pulsectl_async.py", line 521, in subscribe_events
    yield await self._wait_disconnect_or(queue.get())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/pulsectl_asyncio-1.3.0/pulsectl_asyncio/pulsectl_async.py", line 182, in _wait_disconnect_or
    raise PulseDisconnected()
pulsectl.pulsectl.PulseDisconnected
.Assertion 'c' failed at ../src/pulse/subscribe.c:64, function pa_context_subscribe(). Aborting.
/var/tmp/rpm-tmp.NiInmB: line 57:   222 Aborted                    (core dumped) CFLAGS="${CFLAGS:-${RPM_OPT_FLAGS}}" LDFLAGS="${LDFLAGS:-${RPM_LD_FLAGS}}" PATH="/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/BUILDROOT/usr/bin:$PATH" PYTHONPATH="${PYTHONPATH:-/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/BUILDROOT/usr/lib64/python3.15/site-packages:/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/BUILDROOT/usr/lib/python3.15/site-packages}" PYTHONDONTWRITEBYTECODE=1 PYTEST_ADDOPTS="${PYTEST_ADDOPTS:-} --ignore=/builddir/build/BUILD/python-pulsectl-asyncio-1.3.0-build/.pyproject-builddir" PYTEST_XDIST_AUTO_NUM_WORKERS="${PYTEST_XDIST_AUTO_NUM_WORKERS:-8}" /usr/bin/python3 -m unittest discover

RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.NiInmB (%check)
```

**Comment by mhthies** [comment]
Thanks for the new try and sorry that it still doesn't work. The longer output is actually from two or three different errors: One unittest fails (for a yet unknown reason), one unittest triggers the long output about an exception in an async coroutine which is never retrieved and finally, another unittest results in the C assertion error which crashes the program.

I could not spot the issue and so I tried to reproduce it in a Fedora container. And I found the root cause: The tests require the `paplay` executable which – on fedora – is not installed with the `pulseaudio` package, but **requires the `pulseaudio-utils` package, in addition**. Adding it as a build/test dependency should fix your issue.

However, I will try to fix the code to handle this error condition more gradefully (avoid the C assertion error and skip tests that require `paplay` if not installed).
